services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false 